#!/usr/bin/env python3
"""Convert a locally generated eduPIC 1.0 table into AuroraPIC manifests.

This tool contains no eduPIC cross-section formula. It consumes the six-column
``cross_sections.dat`` produced locally by the pinned upstream implementation,
validates the exact grid and channel contract, and writes separate electron
and ion gas packages. Generated data remain local and are not redistributed by
AuroraPIC.
"""

from __future__ import annotations

import argparse
from datetime import date
import hashlib
import json
import math
import os
from pathlib import Path
import shutil
import tempfile
from typing import Iterable, TextIO


PINNED_COMMIT = "32050728c961a317d6d6acd6bc86d026da403326"
PINNED_SOURCE_SHA256 = (
    "7c7679c0f0c98844940ea911bbb7581ec33f818e8d14427c9837ffdcf1ecea41"
)
EXPECTED_ROWS = 1_000_000
ENERGY_STEP_EV = 0.001
ELECTRON_MASS_KG = 9.10938356e-31
ARGON_MASS_KG = 6.63352090e-26
EV_TO_J = 1.60217662e-19
K_BOLTZMANN = 1.38064852e-23
PRESSURE_PA = 10.0
TEMPERATURE_K = 350.0
EXCITATION_THRESHOLD_EV = 11.5
IONIZATION_THRESHOLD_EV = 15.8
IONIZATION_EJECTED_SCALE_EV = 10.0


class ImportFailure(RuntimeError):
    """Raised when the local source cannot satisfy the pinned contract."""


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as stream:
            for block in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(block)
    except OSError as error:
        raise ImportFailure(f"cannot read {path}: {error}") from error
    return digest.hexdigest()


def parse_row(line: str, source: Path, line_number: int) -> tuple[float, ...]:
    fields = line.split()
    if len(fields) != 6:
        raise ImportFailure(
            f"{source}:{line_number}: expected energy plus five cross sections"
        )
    try:
        values = tuple(float(field) for field in fields)
    except ValueError as error:
        raise ImportFailure(
            f"{source}:{line_number}: invalid numeric value"
        ) from error
    if any(not math.isfinite(value) for value in values):
        raise ImportFailure(f"{source}:{line_number}: non-finite value")
    if any(value < 0.0 for value in values):
        raise ImportFailure(f"{source}:{line_number}: negative value")
    return values


def write_manifest(
    path: Path,
    *,
    projectile: str,
    retrieved: str,
) -> None:
    common = (
        "gas_data_version = 2\n"
        "units = si\n"
        "gas = argon\n"
        f"neutral_mass = {ARGON_MASS_KG:.17g}\n"
        f"dataset_id = edupic.1.0.default-argon.{projectile}\n"
        f"dataset_version = {PINNED_COMMIT}\n"
        "data_provenance = Locally generated by pinned eduPIC 1.0 "
        "test_cross_sections output\n"
        "citation = Donko et al., Plasma Sources Sci. Technol. 30 "
        "095017 (2021), eduPIC 1.0\n"
        f"retrieved = {retrieved}\n"
        "license = GPL-3.0-derived local generated data, redistribution "
        "requires independent review\n"
    )
    if projectile == "electron":
        channels = f"""

[collision.elastic]
type = elastic
cross_section_file = electron_elastic.dat
energy_scale = {EV_TO_J:.17g}
cross_section_interpolation = lower_bin
angular_model = isotropic

[collision.excitation]
type = excitation
cross_section_file = electron_excitation.dat
energy_scale = {EV_TO_J:.17g}
cross_section_interpolation = lower_bin
threshold_energy = {EXCITATION_THRESHOLD_EV * EV_TO_J:.17g}

[collision.ionization]
type = ionization
cross_section_file = electron_ionization.dat
energy_scale = {EV_TO_J:.17g}
cross_section_interpolation = lower_bin
threshold_energy = {IONIZATION_THRESHOLD_EV * EV_TO_J:.17g}
ionization_kinematics = opal_beaty_peterson
ionization_ejected_energy_scale = {IONIZATION_EJECTED_SCALE_EV * EV_TO_J:.17g}
"""
    elif projectile == "ion":
        channels = f"""

[collision.isotropic]
type = elastic
cross_section_file = ion_isotropic.dat
energy_scale = {EV_TO_J:.17g}
cross_section_interpolation = lower_bin
energy_frame = center_of_mass
angular_model = isotropic

[collision.backward]
type = elastic
cross_section_file = ion_backward.dat
energy_scale = {EV_TO_J:.17g}
cross_section_interpolation = lower_bin
energy_frame = center_of_mass
angular_model = backward
"""
    else:
        raise ImportFailure(f"unsupported projectile manifest: {projectile}")
    path.write_text(common + channels, encoding="utf-8")


def rate_coefficient(energy_ev: float, sigma: float, mass: float) -> float:
    speed = math.sqrt(2.0 * energy_ev * EV_TO_J / mass)
    return sigma * speed


def output_identity(path: Path) -> dict[str, object]:
    return {
        "bytes": path.stat().st_size,
        "sha256": sha256(path),
    }


def convert(
    source: Path,
    output_dir: Path,
    *,
    source_sha256: str,
    retrieved: str,
    expected_rows: int = EXPECTED_ROWS,
    energy_step_ev: float = ENERGY_STEP_EV,
) -> dict[str, object]:
    if output_dir.exists():
        raise ImportFailure(f"refusing to overwrite output directory: {output_dir}")
    actual_source_sha256 = sha256(source)
    if actual_source_sha256 != source_sha256:
        raise ImportFailure(
            "source table SHA-256 differs from the explicitly supplied value"
        )
    try:
        date.fromisoformat(retrieved)
    except ValueError as error:
        raise ImportFailure("retrieved must be a valid YYYY-MM-DD date") from error
    if expected_rows < 2 or energy_step_ev <= 0.0:
        raise ImportFailure("invalid expected source-grid contract")

    output_dir.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{output_dir.name}.", dir=output_dir.parent)
    )
    names = (
        "electron_elastic.dat",
        "electron_excitation.dat",
        "electron_ionization.dat",
        "ion_isotropic.dat",
        "ion_backward.dat",
    )
    streams: list[TextIO] = []
    maxima = {
        "electron_sigma_v_m3_s": 0.0,
        "electron_peak_energy_ev": 0.0,
        "ion_sigma_v_m3_s": 0.0,
        "ion_peak_energy_com_ev": 0.0,
    }
    try:
        for name in names:
            stream = (temporary / name).open("w", encoding="utf-8")
            stream.write("# Local conversion of pinned eduPIC 1.0 output\n")
            stream.write("# energy_eV cross_section_m2\n")
            streams.append(stream)
        row_count = 0
        with source.open("r", encoding="utf-8", errors="strict") as input_stream:
            for line_number, line in enumerate(input_stream, 1):
                stripped = line.strip()
                if not stripped:
                    raise ImportFailure(
                        f"{source}:{line_number}: blank rows are not permitted"
                    )
                values = parse_row(stripped, source, line_number)
                energy, *cross_sections = values
                expected_energy = row_count * energy_step_ev
                if not math.isclose(
                    energy, expected_energy, rel_tol=0.0, abs_tol=5.0e-10
                ):
                    raise ImportFailure(
                        f"{source}:{line_number}: energy grid mismatch "
                        f"({energy} != {expected_energy})"
                    )
                if energy <= EXCITATION_THRESHOLD_EV and cross_sections[1] != 0.0:
                    raise ImportFailure(
                        f"{source}:{line_number}: excitation is nonzero at or below threshold"
                    )
                if energy <= IONIZATION_THRESHOLD_EV and cross_sections[2] != 0.0:
                    raise ImportFailure(
                        f"{source}:{line_number}: ionization is nonzero at or below threshold"
                    )
                for stream, cross_section in zip(streams, cross_sections):
                    stream.write(f"{energy:.17g} {cross_section:.17g}\n")

                electron_sigma = sum(cross_sections[:3])
                electron_rate = rate_coefficient(
                    energy, electron_sigma, ELECTRON_MASS_KG
                )
                if electron_rate > maxima["electron_sigma_v_m3_s"]:
                    maxima["electron_sigma_v_m3_s"] = electron_rate
                    maxima["electron_peak_energy_ev"] = energy
                ion_sigma = sum(cross_sections[3:])
                ion_rate = rate_coefficient(
                    energy, ion_sigma, ARGON_MASS_KG / 2.0
                )
                if ion_rate > maxima["ion_sigma_v_m3_s"]:
                    maxima["ion_sigma_v_m3_s"] = ion_rate
                    maxima["ion_peak_energy_com_ev"] = energy
                row_count += 1
                if row_count > expected_rows:
                    raise ImportFailure(
                        f"{source}: source contains more than {expected_rows} rows"
                    )
        if row_count != expected_rows:
            raise ImportFailure(
                f"{source}: expected {expected_rows} rows, found {row_count}"
            )
        for stream in streams:
            stream.close()
        streams.clear()

        write_manifest(
            temporary / "edupic_argon_electron.gas",
            projectile="electron",
            retrieved=retrieved,
        )
        write_manifest(
            temporary / "edupic_argon_ion.gas",
            projectile="ion",
            retrieved=retrieved,
        )
        neutral_density = PRESSURE_PA / (K_BOLTZMANN * TEMPERATURE_K)
        artifacts = {
            path.name: output_identity(path)
            for path in sorted(temporary.iterdir())
            if path.name != "audit.json"
        }
        audit: dict[str, object] = {
            "edupic_cross_section_import_version": 1,
            "case_id": "edupic-1.0-default-argon-ccp",
            "source": {
                "table": str(source.resolve()),
                "table_sha256": actual_source_sha256,
                "repository": "https://github.com/donkozoltan/eduPIC",
                "commit": PINNED_COMMIT,
                "implementation": "C/eduPIC.cc",
                "implementation_sha256": PINNED_SOURCE_SHA256,
                "generation_entry_point": "test_cross_sections",
            },
            "contract": {
                "rows": row_count,
                "energy_step_ev": energy_step_ev,
                "maximum_energy_ev": (row_count - 1) * energy_step_ev,
                "columns": [
                    "energy_ev",
                    "electron_elastic_m2",
                    "electron_excitation_m2",
                    "electron_ionization_m2",
                    "ion_isotropic_m2",
                    "ion_backward_m2",
                ],
                "excitation_threshold_ev": EXCITATION_THRESHOLD_EV,
                "ionization_threshold_ev": IONIZATION_THRESHOLD_EV,
                "ionization_kinematics": "opal_beaty_peterson",
                "ionization_ejected_energy_scale_ev": IONIZATION_EJECTED_SCALE_EV,
                "ion_energy_frame": "center_of_mass",
                "cross_section_interpolation": "lower_bin",
            },
            "reference_operating_point": {
                "pressure_pa": PRESSURE_PA,
                "temperature_k": TEMPERATURE_K,
                "neutral_density_m3": neutral_density,
            },
            "grid_rate_envelope": {
                **maxima,
                "electron_peak_frequency_s": (
                    maxima["electron_sigma_v_m3_s"] * neutral_density
                ),
                "ion_peak_frequency_s": (
                    maxima["ion_sigma_v_m3_s"] * neutral_density
                ),
                "scope": "stationary-target source energy grid only",
            },
            "artifacts": artifacts,
            "license_boundary": (
                "Generated locally from GPL-3.0 eduPIC source and intentionally "
                "not tracked or redistributed by AuroraPIC"
            ),
            "physics_claim": "none_data_conversion_only",
        }
        (temporary / "audit.json").write_text(
            json.dumps(audit, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        temporary.rename(output_dir)
        return audit
    except Exception:
        for stream in streams:
            stream.close()
        shutil.rmtree(temporary, ignore_errors=True)
        raise


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument(
        "--source-sha256",
        required=True,
        help="Explicit SHA-256 of the locally generated source table",
    )
    parser.add_argument("--retrieved", default=date.today().isoformat())
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] | None = None) -> int:
    args = parse_args(os.sys.argv[1:] if argv is None else argv)
    try:
        audit = convert(
            args.source,
            args.output_dir,
            source_sha256=args.source_sha256,
            retrieved=args.retrieved,
        )
    except (ImportFailure, OSError, UnicodeError) as error:
        print(f"eduPIC cross-section import failed: {error}", file=os.sys.stderr)
        return 2
    print(
        "wrote pinned eduPIC electron and ion gas packages to "
        f"{args.output_dir} ({audit['contract']['rows']} rows)",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
