#!/usr/bin/env python3
"""Instrument a local eduPIC 1.0 source with passive electron surface flux.

The GPL source itself remains user supplied and local.  This deterministic
transform accepts only the pinned upstream source used by the AuroraPIC eduPIC
campaign, adds no random draws, makes the otherwise unrecorded continuation
seed explicit, and writes phase-resolved electron crossing
counts and kinetic energies at x/L = 0.2 and 0.6.  The diagnostic mirrors
AuroraPIC's drift-crossing convention and 200-phase, 0.25 eV histogram.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


EXPECTED_SOURCE_SHA256 = (
    "ff339feebe0b5732e926e8d3f9c144573828b6a2202d43ed9247f1e1f579c907"
)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256(path: Path) -> str:
    return sha256_bytes(path.read_bytes())


def replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one source anchor, found {count}")
    return source.replace(old, new, 1)


def instrument(source: str) -> str:
    source = replace_once(
        source,
        "#include <string>\n",
        "#include <string>\n#include <cstdlib>\n",
        "environment include",
    )
    source = replace_once(
        source,
        """std::random_device rd{}; 
std::mt19937 MTgen(rd());
""",
        """unsigned int diagnostic_rng_seed(){
    const char* value = std::getenv("EDUPIC_DIAGNOSTIC_SEED");
    if (value == nullptr) return 12345u;
    return static_cast<unsigned int>(stoul(value));
}
std::mt19937 MTgen(diagnostic_rng_seed());
""",
        "deterministic continuation seed",
    )
    source = replace_once(
        source,
        "Ullong    N_i_coll                   = 0;                 // counter for ion collisions\n",
        """Ullong    N_i_coll                   = 0;                 // counter for ion collisions

// Passive phase-resolved internal electron surface-flux diagnostic.
// Generated by AuroraPIC's instrument_edupic_surface_flux.py.
const int SURFACE_FLUX_SURFACES = 2;
const int SURFACE_FLUX_DIRECTIONS = 2;
const int SURFACE_FLUX_ENERGY_BINS = 320;
const double SURFACE_FLUX_ENERGY_MAX_EV = 80.0;
const double surface_flux_positions[SURFACE_FLUX_SURFACES] = {0.2 * L, 0.6 * L};
using surface_flux_scalar = array<double,N_XT*SURFACE_FLUX_SURFACES*SURFACE_FLUX_DIRECTIONS>;
using surface_flux_count = array<Ullong,N_XT*SURFACE_FLUX_SURFACES*SURFACE_FLUX_DIRECTIONS>;
using surface_flux_histogram = array<double,N_XT*SURFACE_FLUX_SURFACES*SURFACE_FLUX_DIRECTIONS*SURFACE_FLUX_ENERGY_BINS>;
surface_flux_count surface_flux_macro_crossings = {0};
surface_flux_count surface_flux_overflow_macro_crossings = {0};
surface_flux_scalar surface_flux_kinetic_energy_joule = {0.0};
surface_flux_histogram surface_flux_histogram_macro = {0.0};
""",
        "surface accumulator insertion",
    )

    source = replace_once(
        source,
        """//---------------------------------------------------------------------//
// simulation of one radiofrequency cycle                              //
//---------------------------------------------------------------------//

void do_one_cycle (void){
""",
        """//-------------------------------------------------------------------------//
// passive phase-resolved internal electron surface-flux diagnostic       //
//-------------------------------------------------------------------------//

void measure_electron_surface_crossings(double old_x, double new_x,
                                        double vx, double vy, double vz,
                                        size_t phase){
    const double energy_joule = 0.5 * E_MASS * (vx*vx + vy*vy + vz*vz);
    const double energy_eV = energy_joule / EV_TO_J;
    for (size_t surface=0; surface<SURFACE_FLUX_SURFACES; ++surface) {
        size_t direction = SURFACE_FLUX_DIRECTIONS;
        if (old_x < surface_flux_positions[surface] &&
            new_x >= surface_flux_positions[surface]) direction = 0;
        else if (old_x > surface_flux_positions[surface] &&
                 new_x <= surface_flux_positions[surface]) direction = 1;
        if (direction == SURFACE_FLUX_DIRECTIONS) continue;
        const size_t scalar =
            (phase * SURFACE_FLUX_SURFACES + surface) *
            SURFACE_FLUX_DIRECTIONS + direction;
        surface_flux_macro_crossings[scalar]++;
        surface_flux_kinetic_energy_joule[scalar] += energy_joule;
        if (energy_eV >= SURFACE_FLUX_ENERGY_MAX_EV) {
            surface_flux_overflow_macro_crossings[scalar]++;
        } else {
            const size_t bin = min(
                static_cast<size_t>(energy_eV /
                    (SURFACE_FLUX_ENERGY_MAX_EV /
                     static_cast<double>(SURFACE_FLUX_ENERGY_BINS))),
                static_cast<size_t>(SURFACE_FLUX_ENERGY_BINS - 1));
            const size_t histogram =
                scalar * SURFACE_FLUX_ENERGY_BINS + bin;
            surface_flux_histogram_macro[histogram] += 1.0;
        }
    }
}

void save_surface_flux(void){
    ofstream histogram("edupic_phase_surface_flux.csv");
    ofstream summary("edupic_phase_surface_flux_summary.csv");
    histogram << setprecision(17);
    summary << setprecision(17);
    histogram << "phase_bin,phase_fraction,surface_id,position_m,direction,energy_bin,energy_eV,represented_crossings_m-2,probability_density_eV-1\\n";
    summary << "phase_bin,phase_fraction,surface_id,position_m,direction,macro_crossings,overflow_macro_crossings,represented_crossings_m-2,overflow_fraction,represented_particle_flux_m-2_s-1,kinetic_energy_flux_W_m-2\\n";
    const double bin_width = SURFACE_FLUX_ENERGY_MAX_EV /
        static_cast<double>(SURFACE_FLUX_ENERGY_BINS);
    const double represented_per_macro = WEIGHT / ELECTRODE_AREA;
    const double phase_duration = static_cast<double>(no_of_cycles) *
        PERIOD / static_cast<double>(N_XT);
    for (size_t phase=0; phase<N_XT; ++phase) {
        const double phase_fraction =
            (static_cast<double>(phase) + 0.5) / static_cast<double>(N_XT);
        for (size_t surface=0; surface<SURFACE_FLUX_SURFACES; ++surface) {
            for (size_t direction=0; direction<SURFACE_FLUX_DIRECTIONS; ++direction) {
                const size_t scalar =
                    (phase * SURFACE_FLUX_SURFACES + surface) *
                    SURFACE_FLUX_DIRECTIONS + direction;
                const double represented =
                    static_cast<double>(surface_flux_macro_crossings[scalar]) *
                    represented_per_macro;
                const char* direction_name =
                    direction == 0 ? "left_to_right" : "right_to_left";
                for (size_t bin=0; bin<SURFACE_FLUX_ENERGY_BINS; ++bin) {
                    const double represented_bin =
                        surface_flux_histogram_macro[
                            scalar * SURFACE_FLUX_ENERGY_BINS + bin] *
                        represented_per_macro;
                    histogram << phase << ',' << phase_fraction << ','
                        << surface << ',' << surface_flux_positions[surface]
                        << ',' << direction_name << ',' << bin << ','
                        << (static_cast<double>(bin) + 0.5) * bin_width << ','
                        << represented_bin << ','
                        << (represented > 0.0
                            ? represented_bin / represented / bin_width : 0.0)
                        << '\\n';
                }
                summary << phase << ',' << phase_fraction << ',' << surface
                    << ',' << surface_flux_positions[surface] << ','
                    << direction_name << ','
                    << surface_flux_macro_crossings[scalar] << ','
                    << surface_flux_overflow_macro_crossings[scalar] << ','
                    << represented << ','
                    << (surface_flux_macro_crossings[scalar] > 0
                        ? static_cast<double>(
                            surface_flux_overflow_macro_crossings[scalar]) /
                            static_cast<double>(surface_flux_macro_crossings[scalar])
                        : 0.0) << ','
                    << represented / phase_duration << ','
                    << surface_flux_kinetic_energy_joule[scalar] *
                        represented_per_macro / phase_duration << '\\n';
            }
        }
    }
}

//---------------------------------------------------------------------//
// simulation of one radiofrequency cycle                              //
//---------------------------------------------------------------------//

void do_one_cycle (void){
""",
        "surface function insertion",
    )

    source = replace_once(
        source,
        """    double   rmod, rint, g, g_sqr, gx, gy, gz, vx_a, vy_a, vz_a, e_x, energy, nu, p_coll, v_sqr, velocity;
""",
        """    double   rmod, rint, g, g_sqr, gx, gy, gz, vx_a, vy_a, vz_a, e_x, energy, nu, p_coll, v_sqr, velocity, old_x;
""",
        "old position declaration",
    )

    source = replace_once(
        source,
        """            // update velocity and position

            vx_e[k] -= e_x * FACTOR_E;
            x_e[k]  += vx_e[k] * DT_E;
""",
        """            // update velocity and position

            old_x = x_e[k];
            vx_e[k] -= e_x * FACTOR_E;
            x_e[k]  += vx_e[k] * DT_E;
            if (measurement_mode) {
                measure_electron_surface_crossings(
                    old_x, x_e[k], vx_e[k], vy_e[k], vz_e[k], t_index);
            }
""",
        "surface crossing call",
    )

    source = replace_once(
        source,
        """    if (measurement_mode) {
        check_and_save_info();
    }
""",
        """    if (measurement_mode) {
        check_and_save_info();
        save_surface_flux();
    }
""",
        "surface output call",
    )
    return source


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--audit", type=Path)
    args = parser.parse_args()
    if not args.source.is_file():
        parser.error(f"source does not exist: {args.source}")
    source_hash = sha256(args.source)
    if source_hash != EXPECTED_SOURCE_SHA256:
        raise RuntimeError(
            f"source hash {source_hash} differs from pinned {EXPECTED_SOURCE_SHA256}"
        )
    output_text = instrument(args.source.read_text(encoding="utf-8"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output_text, encoding="utf-8", newline="\n")
    audit = {
        "schema_version": 1,
        "transform": "passive_edupic_phase_surface_flux_v1",
        "source_sha256": source_hash,
        "instrumented_source_sha256": sha256(args.output),
        "surfaces_gap_fraction": [0.2, 0.6],
        "phase_bins": 200,
        "energy_bins": 320,
        "energy_max_eV": 80.0,
        "crossing_velocity": "post_kick_leapfrog_drift_velocity",
        "rng_initialization": "EDUPIC_DIAGNOSTIC_SEED environment variable; default 12345",
        "random_draws_added": 0,
        "particle_state_mutation_added": False,
    }
    if args.audit:
        args.audit.parent.mkdir(parents=True, exist_ok=True)
        args.audit.write_text(
            json.dumps(audit, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
            newline="\n",
        )
    print(json.dumps(audit, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
